<?php

/**
 * @file
 * REST API module file.
 */

xautoload()->registerModulePsr4(__FILE__, 'src');

use Drupal\restapi\YamlConfigDiscovery;
use Drupal\restapi\RestServices\EntityRestService;

require_once __DIR__ . '/vendor/autoload.php';

/**
 * Implements hook_menu().
 */
function restapi_menu() {
  $config_discovery = new YamlConfigDiscovery();
  $routes = $config_discovery->parsedConfig('restapi.routes');
  cache_clear_all('routes:', 'cache_restapi_config', TRUE);

  $items = array();
  foreach ($routes as $route_name => $route) {
    cache_set("routes:$route_name", $route, 'cache_restapi_config');
    $items[$route['path']] = array(
      'page callback' => 'restapi_callback',
      'page arguments' => array($route_name),
      'delivery callback' => 'restapi_output',
      'access callback'   => TRUE,
    );
    // Set custom callback if one is defined.
    if (isset($route['callback'])) {
      $items[$route['path']]['page callback'] = $route['callback'];
    }
    // Set path wildcards if any are defined.
    if (isset($route['wildcards'])) {
      $page_arguments = array($route_name);
      foreach ($route['wildcards'] as $wildcard) {
        $page_arguments[] = $wildcard;
      }
      $items[$route['path']]['page arguments'] = $page_arguments;
    }
  }

  return $items;
}

/**
 * Basic callback for a REST Service.
 *
 * @param string $route_name
 *   The route identifier.
 * @param string $etid
 *   A passed entity ID if requesting a single entity.
 *
 * @return array
 *   A formatted response to the clients request.
 */
function restapi_callback($route_name, $etid = NULL) {
  $variables = !empty($etid) ? array('etid' => $etid) : array();
  $service = new EntityRestService($route_name, $variables);

  return $service->generateResponse();
}

/**
 * Custom delivery callback to handle REST requests.
 */
function restapi_output($var) {
  if (isset($var)) {
    // We are returning JSON, so tell the browser.
    drupal_add_http_header('Content-Type', 'application/json');
    echo json_encode($var, JSON_UNESCAPED_SLASHES);
  }
}

function restapi_service_config($type, $id, $caching_enabled) {
  $cache = cache_get("$type:$id", 'cache_restapi_config');
  if (!$cache || !$caching_enabled) {
    drupal_add_http_header('X-Drupal-Cache', 'MISS');
    $config_discovery = new YamlConfigDiscovery();
    $yaml = $config_discovery->parsedConfig('restapi.' . $type);
    $data = $yaml[$id];
    if (!empty($data) && $caching_enabled) {
      cache_set("$type:$id", $data, 'cache_restapi_config');
    }
  } else {
    drupal_add_http_header('X-Drupal-Cache', 'HIT');
    $data = $cache->data;
  }
  return $data;
}

/**
 * Implements hook_flush_caches().
 */
function restapi_flush_caches() {
  return array('cache_restapi_config', 'cache_restapi_collections', 'cache_restapi_content', 'cache_restapi_headers');
}

/**
 * Determin the proper empty variable.
 */
function restapi_get_empty($type, $cardinality) {
  if ($cardinality != 1) {
    return array();
  }
  switch ($type) {
    case 'integer':
      return null;
    case 'boolean':
      return false;
    default:
      return '';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter the Performance configuration page to add REST API caching options.
 */
function restapi_form_system_performance_settings_alter(&$form, $form_state, $node) {
  // Take control of new revision and published settings. Only Content Flow
  // should be able to set/alter these.
  $form['caching']['restapi'] = array(
    '#type' => 'fieldset',
    '#title' => t('REST API Caching'),
  );
  $form['caching']['restapi']['restapi_cache_configuration'] = array(
    '#type' => 'checkbox',
    '#title' => t('Cache REST API configuration'),
    '#default_value' => variable_get('restapi_cache_configuration', 0),
  );
  $form['caching']['restapi']['restapi_cache_collections'] = array(
    '#type' => 'checkbox',
    '#title' => t('Cache a requests entity results'),
    '#default_value' => variable_get('restapi_cache_collections', 0),
  );
  $form['caching']['restapi']['restapi_cache_headers'] = array(
    '#type' => 'checkbox',
    '#title' => t('Cache a requests header results'),
    '#default_value' => variable_get('restapi_cache_headers', 0),
  );
  $form['caching']['restapi']['restapi_cache_content'] = array(
    '#type' => 'checkbox',
    '#title' => t('Cache formatted entities.'),
    '#default_value' => variable_get('restapi_cache_content', 0),
  );
}
